
# Errors and Exceptions

* 발생할 수 있는 오류와 예외처리를 확인해봅시다.

# 문법 에러(Syntax Error)

* 가장 많이 만날 수 있는 에러로 발생한 `파일 이름`과 `줄`, `^`을 통해 파이썬이 읽어 들일 때(parser)의 문제 발생 위치를 표현한다.


```python
# if문을 통해 발생시켜봅시다!
if True:
    print('참')
else
    print('거짓')
```


      File "<ipython-input-2-ad301a5287d3>", line 4
        else
            ^
    SyntaxError: invalid syntax




```python
# print문을 통해 다른 오류를 발생시켜봅시다!
# EOL 오류를 봅시다 # End of Line
print('hi)
```


      File "<ipython-input-3-e6626f2cef94>", line 3
        print('hi)
                  ^
    SyntaxError: EOL while scanning string literal




```python
# EOF 에러도 보게 됩니다. # End of File
print('hi'
```


      File "<ipython-input-4-bbe254e9d0ff>", line 2
        print('hi'
                  ^
    SyntaxError: unexpected EOF while parsing




```python
# 정확한 위치를 지정하지 않을 수도 있으므로 앞뒤로 모두 확인을 해봐야합니다.
if True print('참')
```


      File "<ipython-input-5-233330a23b1c>", line 2
        if True print('참')
                    ^
    SyntaxError: invalid syntax




```python
'hi' if True # 조건표현식은 항상 else 키워드까지 표현되어야 함.
```


      File "<ipython-input-6-562d573a7347>", line 1
        'hi' if True
                    ^
    SyntaxError: invalid syntax




```python
[x for x in range(3) if True else False] # list comprehension에서 for문 뒷쪽에 쓰이는 if는 else 키워드랑 같이 쓸 수 있음.(필터!!!)

# 쓰고 싶다면, for문 왼쪽에 조건표현식으로 써야함.
[x if True else False for x in range(3)]
```


      File "<ipython-input-7-559218cce7c6>", line 1
        [x for x in range(3) if True else False]
                                        ^
    SyntaxError: invalid syntax



# 예외 (Exceptions)

* 문법이나 표현식이 바르게 되어있지만, 실행시 발생하는 에러입니다.

* 아래 제시된 모든 에러는 Exception을 상속받아 이뤄집니다.


```python
# ZeroDivisionError를 확인해봅시다.
10 / 0
```


    ---------------------------------------------------------------------------
    
    ZeroDivisionError                         Traceback (most recent call last)
    
    <ipython-input-8-1a1c9c3dae95> in <module>
          1 # ZeroDivisionError를 확인해봅시다.
    ----> 2 10 / 0


    ZeroDivisionError: division by zero



```python
# NameError를 확인해봅시다. 
print(abc)
# 이름 공간(namespace)에서 유효하지 않은 이름 (정의되지 않은 이름)
# 해당 변수명, 혹은 모듈 등이 제대로 선언되었는지 확인
```


    ---------------------------------------------------------------------------
    
    NameError                                 Traceback (most recent call last)
    
    <ipython-input-9-dca2aa9ca288> in <module>
          1 # NameError를 확인해봅시다.
    ----> 2 print(abc)


    NameError: name 'abc' is not defined



```python
random.seed(1) # 모듈이 import 되었는지 확인.
```


    ---------------------------------------------------------------------------
    
    NameError                                 Traceback (most recent call last)
    
    <ipython-input-11-6c3a96d89660> in <module>
    ----> 1 random.seed(1)


    NameError: name 'random' is not defined



```python
# TypeError를 확인해봅시다.
1 + '1'
# 데이터 타입 자체가 잘못 되었을 경우
# 위에서의 오류는 지원되지 않는(unsupported) 연산자(operand) 타입(type) + 기호에 대해서.
```


    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-10-a8978fdced50> in <module>
          1 # TypeError를 확인해봅시다.
    ----> 2 1 + '1'


    TypeError: unsupported operand type(s) for +: 'int' and 'str'



```python
# 함수 호출과정에서 TypeError도 발생하게 됩니다. 확인해봅시다.
round('3.5')
```


    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-12-f45051a456cd> in <module>
          1 # 함수 호출과정에서 TypeError도 발생하게 됩니다. 확인해봅시다.
    ----> 2 round('3.5')


    TypeError: type str doesn't define __round__ method



```python
# 함수호출 과정에서 다양한 오류를 확인할 수 있습니다. : 필수 argument 누락 
round() # 반드시 필요한 인자가 없음.
```


    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-14-36bc3de15b17> in <module>
          1 # 함수호출 과정에서 다양한 오류를 확인할 수 있습니다. : 필수 argument 누락
    ----> 2 round()


    TypeError: round() missing required argument 'number' (pos 1)



```python
import random
random.sample() # 2개의 위치 인자가 부족함.
```


    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-16-876dc5bdd1f4> in <module>
          1 import random
    ----> 2 random.sample()


    TypeError: sample() missing 2 required positional arguments: 'population' and 'k'



```python
# 함수 호출 과정에서 다양한 오류를 확인할 수 있습니다. : argument 많은 경우
round(3, 6, 7) # 2개까지 받을 수 있는데(at most 2), 3개를 줬네(3 given)
```


    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-17-0c1948c69aa0> in <module>
          1 # 함수 호출 과정에서 다양한 오류를 확인할 수 있습니다. : argument 많은 경우
    ----> 2 round(3, 6, 7)


    TypeError: round() takes at most 2 arguments (3 given)



```python
# ValueError를 확인해봅시다
numbers = [1, 2]
numbers.index(3) # 리스트에 3이 없네
```


    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-18-2db15259bf59> in <module>
          1 # ValueError를 확인해봅시다
          2 numbers = [1, 2]
    ----> 3 numbers.index(3)


    ValueError: 3 is not in list



```python
# ValueError를 확인해봅시다.
int('3.5') # 10진수 형태의 문자열만 정수로 바꿀 수 있다.
```


    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-19-1b2cb90bb197> in <module>
          1 # ValueError를 확인해봅시다.
    ----> 2 int('3.5')


    ValueError: invalid literal for int() with base 10: '3.5'



```python
# IndexError를 확인해봅시다.
numbers = [1, 2]
numbers[3]
# index의 범위를 벗어남!
# 반복문 안에서는 몇 번 찍히는지 확인하며 디버깅
```


    ---------------------------------------------------------------------------
    
    IndexError                                Traceback (most recent call last)
    
    <ipython-input-20-cca60f14cac1> in <module>
          1 # IndexError를 확인해봅시다.
          2 numbers = [1, 2]
    ----> 3 numbers[3]


    IndexError: list index out of range



```python
# KeyError를 확인해봅시다.
my_dict = {}
my_dict['hi'] # 딕셔너리에서 발생
```


    ---------------------------------------------------------------------------
    
    KeyError                                  Traceback (most recent call last)
    
    <ipython-input-22-64dbd95b6655> in <module>
          1 # KeyError를 확인해봅시다.
          2 my_dict = {}
    ----> 3 my_dict['hi']


    KeyError: 'hi'



```python
# ModuleNotFoundError를 확인해봅시다.
import reque
```


    ---------------------------------------------------------------------------
    
    ModuleNotFoundError                       Traceback (most recent call last)
    
    <ipython-input-23-d072253467e3> in <module>
          1 # ModuleNotFoundError를 확인해봅시다.
    ----> 2 import reque


    ModuleNotFoundError: No module named 'reque'



```python
# ImportError를 확인해봅시다.
from bs4 import B
# 모듈은 잘 찾았는데, 해당 변수/함수/클래스 등이 없는 경우
```


    ---------------------------------------------------------------------------
    
    ImportError                               Traceback (most recent call last)
    
    <ipython-input-24-96304ce8671a> in <module>
          1 # ImportError를 확인해봅시다.
    ----> 2 from bs4 import B


    ImportError: cannot import name 'B' from 'bs4' (c:\users\student\appdata\local\programs\python\python37-32\lib\site-packages\bs4\__init__.py)



```python
# KeyboardInterrupt를 확인해봅시다.
while True:
    continue

# 주피터노트북 - 정지버튼, 일반적으로 파이썬 실행 환경(bash, cmd)는 ctrl + c를 눌러서 중간에 종료했을 때
```


    ---------------------------------------------------------------------------
    
    KeyboardInterrupt                         Traceback (most recent call last)
    
    <ipython-input-25-72661b1c44a9> in <module>
          1 # KeyboardInterrupt를 확인해봅시다.
          2 while True:
    ----> 3     continue


    KeyboardInterrupt: 


# 예외 처리 

## 기본  - `try` `except`
`try` 구문을 이용하여 예외 처리를 할 수 있습니다.

기본은 다음과 같은 구조를 가지고 있습니다.

```python
try:
    codeblock1
except 예외:
    codeblock2
```

* `try`절이 실행됩니다. 

* 예외가 발생되지 않으면, `except`없이 실행이 종료가 됩니다.

* 예외가 중간에 발생하면, 남은 부분을 수행하지 않고, `except`가 실행됩니다.


```python
# 사용자로부터 값을 받아 정수로 변환하여 출력해봅시다.
num = input('숫자를 입력하세요 : ')
print(int(num))
```

    숫자를 입력하세요 : 5.4

    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-27-db5af38d1c35> in <module>
          1 # 사용자로부터 값을 받아 정수로 변환하여 출력해봅시다.
          2 num = input('숫자를 입력하세요 : ')
    ----> 3 print(int(num))


    ValueError: invalid literal for int() with base 10: '5.4'



```python
# 사용자가 문자열을 넣어 해당 오류(ValueError)가 발생하면, 숫자를 입력하라고 출력해봅시다.
try:
    num = input('정수를 입력하세요 : ')
    print(int(num))
    print('짝짝짝!')
except ValueError:
    print('바보야 정수를 입력하라고')
```

    정수를 입력하세요 : 3.4
    바보야 정수를 입력하라고


## 복수의 예외 처리

* 두 가지 예외를 모두 처리할 수 있습니다. 

```python
try:
    codeblock1
except (예외1, 예외2):
    codeblock2
```


```python
# 100을 사용자가 입력한 값으로 나눈 후 출력하는 코드를 작성해봅시다.
num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
print(100/int(num))
```

    100으로 나누고 싶은 숫자를 입력하세요: 1.2

    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-36-e1e9f5ad0425> in <module>
          1 # 100을 사용자가 입력한 값으로 나눈 후 출력하는 코드를 작성해봅시다.
          2 num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
    ----> 3 print(100/int(num))


    ValueError: invalid literal for int() with base 10: '1.2'



```python
# 문자열일때와 0일때 모두 처리를 해봅시다
try:
    num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
    print(100/int(num))
except (ValueError, ZeroDivisionError):
    print('너 바보니..')
```

    100으로 나누고 싶은 숫자를 입력하세요: 문
    너 바보니..



```python
# 각각 다른 오류를 출력할 수 있습니다.
try:
    num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
    print(100/int(num))
except ValueError:
    print('숫자 맞는지 확인해!')
except ZeroDivisionError:
    print('0으로 나눌 수는 없지...')
except:
    print('무슨 일인지 모르겠지만 오류야...!')
```

    100으로 나누고 싶은 숫자를 입력하세요: 1
    100.0



```python
# 여기서 중요한 내용은 에러가 순차적으로 수행됨으로, 가장 작은 범주부터 시작해야합니다.
try:
    num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
    print(100/int(num))
except Exception: # 제일 큰 범위의 에러
    print('오류!')
except ValueError:
    print('숫자 맞는지 확인해!') # 절대 실행 안됨.
```

    100으로 나누고 싶은 숫자를 입력하세요: 0
    오류!



```python
try:
    num = input('100으로 나누고 싶은 숫자를 입력하세요: ')
    print(100/int(num))
except ValueError:
    print('숫자 맞는지 확인해!')
except Exception:
    print('오류!')
```

    100으로 나누고 싶은 숫자를 입력하세요: 0
    오류!



```python
num = 3
if num > 0:
    print('hi')
elif num > -1:
    print('bye')
```

    hi


## 에러 문구 처리

* 에러 문구를 함께 넘겨줄 수 있습니다.

```python
try:
    codeblock1
except 예외 as e:
    codeblock2
```


```python
# 에러 메세지를 넘겨줄 수도 있습니다.
try:
    a = []
    a[3]
except IndexError as e:
    print(f'오류발생!!!!!!!!!! {e}')
```

    오류발생!!!!!!!!!! list index out of range



```python
a = []
a[3]
```


    ---------------------------------------------------------------------------
    
    IndexError                                Traceback (most recent call last)
    
    <ipython-input-63-9d7b305c5a57> in <module>
          1 a = []
    ----> 2 a[3]


    IndexError: list index out of range


## `else`

* 에러가 발생하지 않는 경우 수행되는 문장은 `else`를 이용합니다.

```python
try:
    codeblock1
except 예외:
    codeblock2
else:
    codeblock3
```


```python
# else를 사용해봅시다.
try:
    numbers = [1, 2, 3]
    number = numbers[3]
except IndexError:
    print('오류!!!')
else:
    print(number * 100)
```

    오류!!!


## `finally` 

* 반드시 수행해야하는 문장은 `finally`를 활용합니다.

```python
try:
    codeblock1
except 예외:
    codeblock2
finally:
    codeblock3
```


```python
# finally를 사용해봅시다.
try:
    a = [1, 2]
    print(a[5])
except Exception:
    print('오류발생..!')
finally:
    print(a)
```

    오류발생..!
    [1, 2]


# 예외 발생시키기

`raise`를 통해 예외를 발생시킬 수 있습니다.


```python
# raise를 사용해봅시다.
raise ValueError('값이 뭔가 잘못 되었다...')
```


    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-73-ad0bfd06e075> in <module>
          1 # raise를 사용해봅시다.
    ----> 2 raise ValueError('값이 뭔가 잘못 되었다...')


    ValueError: 값이 뭔가 잘못 되었다...


## 실습 문제

>양의 정수 두개를 받아 몫과 나머지로 출력하는 함수를 만들어보세요.

`def my_div(num1,num2)`

- num2가 0이여서 발생하는 오류인 경우 **에러메시지**를 출력해주세요.

 예) division by zero 오류가 발생하였습니다.


- 인자가 string이여서 발생하는 경우는 **ValueError와 함께 '숫자를 넣어주세요'를 출력**해주세요.
(실제로 이 경우에 발생하는 것은 TypeError입니다.)

- 정상적인 경우에는 결과를 return합니다.


```python
def my_div(num1, num2):
    try:
        result = divmod(num1, num2)
    except ZeroDivisionError as zero:
        print(f'{zero} 오류가 발생하였습니다.')
    except TypeError:
        raise ValueError('숫자를 넣어주세요')
    else:
        return result
my_div(1, 0)
my_div('1', '5')
```

    integer division or modulo by zero 오류가 발생하였습니다.



    ---------------------------------------------------------------------------
    
    TypeError                                 Traceback (most recent call last)
    
    <ipython-input-80-1c58a7e317c4> in my_div(num1, num2)
          2     try:
    ----> 3         result = divmod(num1, num2)
          4     except ZeroDivisionError as zero:


    TypeError: unsupported operand type(s) for divmod(): 'str' and 'str'


​    
    During handling of the above exception, another exception occurred:


    ValueError                                Traceback (most recent call last)
    
    <ipython-input-80-1c58a7e317c4> in <module>
          9         return result
         10 my_div(1, 0)
    ---> 11 my_div('1', '5')
         12 print(my_div(1, 2))


    <ipython-input-80-1c58a7e317c4> in my_div(num1, num2)
          5         print(f'{zero} 오류가 발생하였습니다.')
          6     except TypeError:
    ----> 7         raise ValueError('숫자를 넣어주세요')
          8     else:
          9         return result


    ValueError: 숫자를 넣어주세요


# `assert`

`assert` 문은 예외를 발생시키는 다른 방법이다. 

보통 상태를 검증하는데 사용되며 무조건 `AssertionError`가 발생한다.

```
assert Boolean expression, error message
```

위의 검증식이 거짓일 경우를 발생한다.

`raise`는 항상 예외를 발생시키고, 지정한 예외가 발생한다는 점에서 다르다.

## 실습 문제

>양의 정수 두개를 받아 몫과 나머지로 출력하는 함수를 만들어보세요.

`def my_div(num1,num2)`

- assert를 활용하여, int가 아닌 경우 AssertionError를 발생시켜봅시다.


```python
def my_div(num1, num2):
    assert isinstance(num1, int) or isinstance(num2, int), '숫자를 입력하지 않았습니다.'
my_div('1', '2')
```


    ---------------------------------------------------------------------------
    
    AssertionError                            Traceback (most recent call last)
    
    <ipython-input-82-e312fc1041c1> in <module>
          1 def my_div(num1, num2):
          2     assert isinstance(num1, int) or isinstance(num2, int), '숫자를 입력하지 않았습니다.'
    ----> 3 my_div('1', '2')


    <ipython-input-82-e312fc1041c1> in my_div(num1, num2)
          1 def my_div(num1, num2):
    ----> 2     assert isinstance(num1, int) or isinstance(num2, int), '숫자를 입력하지 않았습니다.'
          3 my_div('1', '2')


    AssertionError: 숫자를 입력하지 않았습니다.

